# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.html

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "marketing"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "ad_impressions"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "ad_impressions" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "impression_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique impression identifier"
    },
    {
      name        = "campaign_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to campaigns table"
    },
    {
      name        = "ad_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Creative / ad unit identifier"
    },
    {
      name        = "user_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Authenticated user; null if anonymous"
    },
    {
      name        = "device_type"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "desktop | mobile | tablet | ctv"
    },
    {
      name        = "placement"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Ad placement position on the page"
    },
    {
      name        = "was_clicked"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "True if the impression resulted in a click"
    },
    {
      name        = "cost_usd"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Cost of this impression in USD (CPM/CPC)"
    },
    {
      name        = "served_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "UTC timestamp when the ad was served"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
