# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.html

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "marketing"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "campaigns"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "campaigns" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "campaign_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique campaign identifier (UUID)"
    },
    {
      name        = "name"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Campaign display name"
    },
    {
      name        = "channel"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Channel: search | social | display | email | affiliate"
    },
    {
      name        = "objective"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "awareness | consideration | conversion | retention"
    },
    {
      name        = "budget_usd"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Total campaign budget in USD"
    },
    {
      name        = "spent_usd"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Amount spent to date in USD"
    },
    {
      name        = "is_active"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether the campaign is currently running"
    },
    {
      name        = "target_audience"
      type        = "JSON"
      mode        = "NULLABLE"
      description = "Audience targeting criteria as JSON"
    },
    {
      name        = "start_date"
      type        = "DATE"
      mode        = "REQUIRED"
      description = "Campaign start date (UTC)"
    },
    {
      name        = "end_date"
      type        = "DATE"
      mode        = "NULLABLE"
      description = "Campaign end date; null if ongoing"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Record creation timestamp (UTC)"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
