# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.html

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "marketing"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "campaign_conversions"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "campaign_conversions" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "conversion_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique conversion record ID"
    },
    {
      name        = "campaign_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to campaigns table"
    },
    {
      name        = "impression_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "FK to ad_impressions; null for view-through"
    },
    {
      name        = "user_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "FK to users table"
    },
    {
      name        = "conversion_type"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "signup | purchase | lead | app_install"
    },
    {
      name        = "revenue_usd"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Revenue value of the conversion in USD"
    },
    {
      name        = "attribution_model"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "last_click | first_click | linear | data_driven"
    },
    {
      name        = "converted_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "UTC timestamp when the conversion occurred"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
