# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.csv

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "customers"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "customers" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "customer_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique customer identifier (UUID)"
    },
    {
      name        = "email"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Customer email address (unique)"
    },
    {
      name        = "full_name"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Customer full name"
    },
    {
      name        = "country_code"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "ISO 3166-1 alpha-2 country code"
    },
    {
      name        = "tier"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Customer tier: standard | silver | gold | platinum"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Account creation timestamp (UTC)"
    },
    {
      name        = "is_active"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether the account is currently active"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
