# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema.pdf

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "analytics"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "events"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "events" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "event_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique event identifier (UUID v4)"
    },
    {
      name        = "session_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Browser or app session identifier"
    },
    {
      name        = "user_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Authenticated user ID; null for anonymous"
    },
    {
      name        = "event_type"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Event name e.g. page_view click purchase"
    },
    {
      name        = "page_url"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Full URL where the event occurred"
    },
    {
      name        = "referrer_url"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "HTTP referrer URL"
    },
    {
      name        = "device_type"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "desktop | mobile | tablet"
    },
    {
      name        = "os"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Operating system name and version"
    },
    {
      name        = "browser"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Browser name and version"
    },
    {
      name        = "country_code"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "ISO 3166-1 alpha-2 country code"
    },
    {
      name        = "region"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "State or region"
    },
    {
      name        = "properties"
      type        = "RECORD"
      mode        = "NULLABLE"
      description = "Additional properties"
    },
    {
      name        = "properties"
      type        = "REPEATED"
      mode        = "NULLABLE"
      description = "Additional properties"
    },
    {
      name        = "properties"
      type        = "MAP"
      mode        = "NULLABLE"
      description = "Additional properties"
    },
    {
      name        = "timestamp"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Event timestamp"
    },
    {
      name        = "timestamp_micros"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Event timestamp with microsecond precision"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
