# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.json

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "inventory_snapshots"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "inventory_snapshots" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "snapshot_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique snapshot record ID"
    },
    {
      name        = "product_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to products table"
    },
    {
      name        = "warehouse_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Warehouse location identifier"
    },
    {
      name        = "qty_on_hand"
      type        = "INTEGER"
      mode        = "REQUIRED"
      description = "Physical units on hand"
    },
    {
      name        = "qty_reserved"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Units reserved for open orders"
    },
    {
      name        = "reorder_point"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Qty threshold that triggers reorder"
    },
    {
      name        = "snapped_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "UTC timestamp of this snapshot"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
