# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.csv

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "order_items"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "order_items" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "item_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique line-item identifier (UUID)"
    },
    {
      name        = "order_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to orders table"
    },
    {
      name        = "product_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to products table"
    },
    {
      name        = "quantity"
      type        = "INTEGER"
      mode        = "REQUIRED"
      description = "Number of units ordered"
    },
    {
      name        = "unit_price"
      type        = "NUMERIC"
      mode        = "REQUIRED"
      description = "Price per unit at time of order"
    },
    {
      name        = "discount_pct"
      type        = "FLOAT"
      mode        = "NULLABLE"
      description = "Discount percentage applied (0-100)"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
