# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema.csv

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "orders"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "orders" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "order_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique order identifier (UUID)"
    },
    {
      name        = "customer_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Reference to the customer who placed the order"
    },
    {
      name        = "status"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Order status: pending | confirmed | shipped | delivered | cancelled"
    },
    {
      name        = "total_amount"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Total order value including taxes and shipping"
    },
    {
      name        = "currency"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "ISO 4217 currency code (e.g. USD GBP INR)"
    },
    {
      name        = "item_count"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Number of line items in the order"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "UTC timestamp when the order was created"
    },
    {
      name        = "updated_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "UTC timestamp of the last status update"
    },
    {
      name        = "shipped_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "UTC timestamp when the order was shipped"
    },
    {
      name        = "delivery_address"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Full delivery address as a single string"
    },
    {
      name        = "is_gift"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "True if the order is marked as a gift"
    },
    {
      name        = "notes"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Optional customer or ops notes"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
