# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema.html

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "finance"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "payments"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "payments" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "payment_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique payment identifier (UUID v4)"
    },
    {
      name        = "order_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to orders table"
    },
    {
      name        = "customer_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "FK to customers table"
    },
    {
      name        = "method"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Payment method: card | bank_transfer | wallet | crypto"
    },
    {
      name        = "provider"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Payment provider: stripe | paypal | adyen | braintree"
    },
    {
      name        = "amount"
      type        = "NUMERIC"
      mode        = "REQUIRED"
      description = "Payment amount before fees"
    },
    {
      name        = "fee"
      type        = "NUMERIC"
      mode        = "NULLABLE"
      description = "Transaction fee charged by the provider"
    },
    {
      name        = "currency"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "ISO 4217 currency code"
    },
    {
      name        = "status"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "pending | authorised | captured | failed | refunded"
    },
    {
      name        = "is_refund"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "True if this record is a refund"
    },
    {
      name        = "reference_id"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Provider transaction reference"
    },
    {
      name        = "metadata"
      type        = "JSON"
      mode        = "NULLABLE"
      description = "Arbitrary payment metadata from provider"
    },
    {
      name        = "initiated_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "UTC timestamp when payment was initiated"
    },
    {
      name        = "settled_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "UTC timestamp when funds were settled"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
