# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.json

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "products"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "products" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "product_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique product identifier (UUID)"
    },
    {
      name        = "sku"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Stock-keeping unit code"
    },
    {
      name        = "name"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Product display name"
    },
    {
      name        = "category"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Top-level product category"
    },
    {
      name        = "sub_category"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Product sub-category"
    },
    {
      name        = "price_usd"
      type        = "NUMERIC"
      mode        = "REQUIRED"
      description = "Current list price in USD"
    },
    {
      name        = "stock_qty"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Units available in warehouse"
    },
    {
      name        = "is_active"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether the product is listed"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Product listing creation timestamp (UTC)"
    },
    {
      name        = "metadata"
      type        = "JSON"
      mode        = "NULLABLE"
      description = "Arbitrary product attributes"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
