# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema_multi.json

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "sales"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "suppliers"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "suppliers" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "supplier_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique supplier identifier"
    },
    {
      name        = "name"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Supplier company name"
    },
    {
      name        = "country_code"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "ISO 3166-1 alpha-2 country"
    },
    {
      name        = "lead_days"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "Typical lead time in days"
    },
    {
      name        = "rating"
      type        = "FLOAT"
      mode        = "NULLABLE"
      description = "Internal supplier rating (0-5)"
    },
    {
      name        = "is_preferred"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether this is a preferred supplier"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Supplier record creation timestamp"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
