# Generated by ai-learning-agents BQ Terraform workflow
# Source: data/raw/schema.json

# ── Variables ────────────────────────────────────────────────────────────────

variable "project_id" {
  description = "GCP project ID"
  type        = string
  default     = "my-gcp-project"
}

variable "dataset_id" {
  description = "BigQuery dataset ID"
  type        = string
  default     = "core"
}

variable "table_id" {
  description = "BigQuery table ID"
  type        = string
  default     = "users"
}

# ── BigQuery Table ────────────────────────────────────────────────────────────

resource "google_bigquery_table" "users" {
  project    = var.project_id
  dataset_id = var.dataset_id
  table_id   = var.table_id

  deletion_protection = false

  schema = jsonencode([
    {
      name        = "user_id"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "Unique user identifier (UUID v4)"
    },
    {
      name        = "email"
      type        = "STRING"
      mode        = "REQUIRED"
      description = "User email address (unique)"
    },
    {
      name        = "display_name"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Public-facing display name"
    },
    {
      name        = "role"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "User role: admin | editor | viewer"
    },
    {
      name        = "is_active"
      type        = "BOOLEAN"
      mode        = "NULLABLE"
      description = "Whether the account is active"
    },
    {
      name        = "subscription_tier"
      type        = "STRING"
      mode        = "NULLABLE"
      description = "Subscription level: free | pro | enterprise"
    },
    {
      name        = "credits_remaining"
      type        = "INTEGER"
      mode        = "NULLABLE"
      description = "API credits remaining in the current billing cycle"
    },
    {
      name        = "created_at"
      type        = "TIMESTAMP"
      mode        = "REQUIRED"
      description = "Account creation timestamp (UTC)"
    },
    {
      name        = "last_login_at"
      type        = "TIMESTAMP"
      mode        = "NULLABLE"
      description = "Most recent successful login timestamp (UTC)"
    },
    {
      name        = "metadata"
      type        = "JSON"
      mode        = "NULLABLE"
      description = "Arbitrary key-value metadata attached to the user"
    }
  ])

  lifecycle {
    prevent_destroy = true
  }
}
